#!/usr/bin/env python3
import os as _os_timing, time as _time_module
if _os_timing.environ.get('TW_TIMING'):
    import atexit as _atexit
    _t0 = _time_module.perf_counter()

    def _report_timing(_f=__file__):
        elapsed = (_time_module.perf_counter() - _t0) * 1000
        import os.path as _osp
        print(f"[timing] {_osp.basename(_f)}: {elapsed:.1f}ms", file=__import__('sys').stderr)

    _atexit.register(_report_timing)

"""
matrix-taskbot - Taskwarrior Matrix bot
Version: 0.1.1

Listens for commands in Matrix DMs and runs Taskwarrior queries/adds.

Usage:
  python3 matrix-taskbot.py           # run bot (uses saved credentials)
  python3 matrix-taskbot.py --login   # first-time login, saves access token
  python3 matrix-taskbot.py --debug   # run with debug logging to stderr + log file

Commands (send in DM to bot):
  help               this message
  list [filter]      task [filter] list
  next               task next
  add <description>  task add <description> [+tag] [project:foo]
  <id>               task <id> information

Install:
  pip install matrix-nio
  cp matrix-taskbot.py ~/.task/scripts/
  cp matrix-taskbot.rc ~/.task/config/   # then edit it
  python3 ~/.task/scripts/matrix-taskbot.py --login
  python3 ~/.task/scripts/matrix-taskbot.py
"""

# ============================================================================
# DEBUG VERSION - Auto-generated by make-awesome.py
# ============================================================================

import os
import sys
from pathlib import Path
from datetime import datetime
import asyncio
import json
import subprocess

# Debug configuration (default 0, triggered by tw --debug=2)
DEBUG_MODE = 0

tw_debug_level = os.environ.get('TW_DEBUG', '0')
try:
    tw_debug_level = int(tw_debug_level)
except ValueError:
    tw_debug_level = 0

debug_active = DEBUG_MODE == 1 or tw_debug_level >= 2

def get_log_dir():
    cwd = Path.cwd()
    if (cwd / '.git').exists():
        log_dir = cwd / 'logs' / 'debug'
    else:
        log_dir = Path.home() / '.task' / 'logs' / 'debug'
    log_dir.mkdir(parents=True, exist_ok=True)
    return log_dir

if debug_active:
    DEBUG_LOG_DIR = get_log_dir()
    DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
    try:
        script_name = Path(__file__).stem
    except:
        script_name = Path(sys.argv[0]).stem if sys.argv else "script"
    DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
    
    def debug_log(message, level=1):
        if debug_active and tw_debug_level >= level:
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
    
    with open(DEBUG_LOG_FILE, "w") as f:
        f.write("=" * 70 + "\n")
        f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        f.write(f"Script: {script_name}\n")
        f.write(f"TW_DEBUG Level: {tw_debug_level}\n")
        f.write("=" * 70 + "\n\n")
    debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)
else:
    def debug_log(message, level=1):
        pass

# ============================================================================
# Original Code
# ============================================================================

VERSION     = '0.1.5'
CONFIG_FILE = Path.home() / '.task' / 'config' / 'matrix-taskbot.rc'
CREDS_FILE  = Path.home() / '.task' / 'config' / '.matrix-taskbot.creds'

HELP_TEXT = f"""\
matrix-taskbot v{VERSION} — Taskwarrior from Matrix

  <id>               task <id> information
  <report>           any named report (next, work, home, …)
  <filter>           any filter (+tag, project:foo, …)
  add <desc>         add task (tags, project, due etc. as normal)
  modify …           modify tasks
  done / delete …    complete or delete tasks
  log / annotate …   log or annotate tasks
  help               this message
""".strip()


# ── Config ────────────────────────────────────────────────────────────────────

def load_config() -> dict:
    cfg = {
        'homeserver':    'https://matrix.org',
        'bot_user':      '',
        'allowed_users': '',
        'max_output':    '40',
        'task':          'task',
    }
    if not CONFIG_FILE.exists():
        return cfg
    for line in CONFIG_FILE.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith('#'):
            continue
        if '=' in line:
            key, _, val = line.partition('=')
            cfg[key.strip()] = val.strip()
    return cfg


# ── Credentials ───────────────────────────────────────────────────────────────

def load_creds() -> dict:
    if CREDS_FILE.exists():
        return json.loads(CREDS_FILE.read_text())
    return {}


def save_creds(access_token: str, device_id: str):
    CREDS_FILE.parent.mkdir(parents=True, exist_ok=True)
    CREDS_FILE.write_text(json.dumps({
        'access_token': access_token,
        'device_id':    device_id,
    }))
    CREDS_FILE.chmod(0o600)


# ── Task runner ───────────────────────────────────────────────────────────────

def run_task(task_bin: str, args: list, max_lines: int = 40, hooks: bool = False) -> str:
    rc_hooks = 'rc.hooks=on' if hooks else 'rc.hooks=off'
    try:
        result = subprocess.run(
            [task_bin, rc_hooks, 'rc.color=off', 'rc.verbose=label,blank']
            + args,
            capture_output=True, text=True, timeout=15,
        )
        out = (result.stdout + result.stderr).strip()
        if not out:
            return '(no output)'
        lines = out.splitlines()
        if len(lines) > max_lines:
            lines = lines[:max_lines] + [f'… ({len(lines) - max_lines} more lines)']
        return '\n'.join(lines)
    except subprocess.TimeoutExpired:
        return '[error] task timed out'
    except Exception as e:
        return f'[error] {e}'


# ── Command parser ────────────────────────────────────────────────────────────

WRITE_VERBS = {
    'add', 'done', 'delete', 'modify', 'start', 'stop',
    'log', 'annotate', 'append', 'prepend', 'denotate',
    'duplicate', 'purge', 'undo',
}

def handle_command(body: str, cfg: dict) -> str:
    body  = body.strip()
    lower = body.lower()
    task  = cfg['task']
    maxl  = int(cfg.get('max_output', 40))

    if lower in ('help', '?', 'h'):
        return HELP_TEXT

    if lower in ('next', 'n'):
        return run_task(task, ['next'], maxl)

    if lower.startswith('add '):
        rest = body[4:].strip()
        if not rest:
            return 'Usage: add <description> [+tag] [project:foo] [due:tomorrow]'
        return run_task(task, ['add'] + rest.split(), maxl, hooks=True)

    if lower.startswith('list') or lower.startswith('ls'):
        parts = body.split(None, 1)
        filter_args = parts[1].split() if len(parts) > 1 else []
        return run_task(task, filter_args + ['list'], maxl)

    # bare number → task info
    if body.isdigit():
        return run_task(task, [body, 'information'], maxl)

    # write verbs: hooks on, pass straight through
    first = lower.split()[0] if lower.split() else ''
    if first in WRITE_VERBS:
        return run_task(task, body.split(), maxl, hooks=True)

    # fallback: treat as filter + list
    return run_task(task, body.split() + ['list'], maxl)


# ── Bot ───────────────────────────────────────────────────────────────────────

async def run_bot(cfg: dict, creds: dict):
    from nio import AsyncClient, RoomMessageText, InviteEvent, InviteMemberEvent

    allowed = {u.strip() for u in cfg['allowed_users'].split(',') if u.strip()}

    client            = AsyncClient(cfg['homeserver'], cfg['bot_user'])
    client.access_token = creds['access_token']
    client.device_id    = creds['device_id']
    client.user_id      = cfg['bot_user']

    async def on_message(room, event):
        debug_log(f'message from {event.sender} in {room.room_id}: {event.body!r}')
        if not isinstance(event, RoomMessageText):
            return
        if event.sender == cfg['bot_user']:
            return
        if allowed and event.sender not in allowed:
            debug_log(f'ignored: {event.sender} not in allowed_users')
            return
        reply = handle_command(event.body, cfg)
        await client.room_send(
            room_id      = room.room_id,
            message_type = 'm.room.message',
            content      = {'msgtype': 'm.text', 'body': reply},
        )

    pending_joins = set()

    async def on_invite(room, event):
        room_id = room.room_id if hasattr(room, 'room_id') else room
        debug_log(f'invite from {event.sender} to {room_id}')
        if allowed and event.sender not in allowed:
            debug_log(f'invite ignored: {event.sender} not in allowed_users')
            return
        pending_joins.add(room_id)
        asyncio.create_task(do_pending_joins())

    async def do_pending_joins():
        from nio import JoinError
        for room_id in list(pending_joins):
            debug_log(f'joining {room_id}')
            resp = await client.join(room_id)
            if isinstance(resp, JoinError):
                debug_log(f'join failed: {resp.message} — declining')
                await client.room_leave(room_id)
            else:
                debug_log(f'joined: {resp.room_id}')
            pending_joins.discard(room_id)

    from nio import Event as NioEvent
    async def on_any(room, event):
        debug_log(f'event: {type(event).__name__} from {event.sender} in {room.room_id}')

    client.add_event_callback(on_message, RoomMessageText)
    client.add_event_callback(on_any,     NioEvent)
    client.add_event_callback(on_invite,  InviteEvent)
    client.add_event_callback(on_invite,  InviteMemberEvent)

    print(f'[matrix-taskbot] v{VERSION} running as {cfg["bot_user"]}')
    print(f'[matrix-taskbot] allowed users: {cfg["allowed_users"] or "(anyone)"}')

    # Initial sync — collect pending invites, then join after sync completes
    await client.sync(timeout=30_000, full_state=True)
    # Also pick up any invites not caught by callback
    for room_id in client.invited_rooms:
        pending_joins.add(room_id)
    await do_pending_joins()
    debug_log(f'joined rooms: {list(client.rooms.keys())}')

    debug_log('sync_forever starting...')
    await client.sync_forever(timeout=30_000, full_state=True)


# ── Login helper ──────────────────────────────────────────────────────────────

async def do_login(cfg: dict):
    from nio import AsyncClient, LoginResponse
    import getpass

    client   = AsyncClient(cfg['homeserver'], cfg['bot_user'])
    password = getpass.getpass(f'Password for {cfg["bot_user"]}: ')
    resp     = await client.login(password)

    if not isinstance(resp, LoginResponse):
        print(f'Login failed: {resp}')
        await client.close()
        sys.exit(1)

    save_creds(resp.access_token, resp.device_id)
    print(f'[matrix-taskbot] Logged in. Credentials saved to {CREDS_FILE}')
    await client.close()


# ── Entry point ───────────────────────────────────────────────────────────────

def main():
    global debug_active, DEBUG_LOG_DIR, DEBUG_SESSION_ID, DEBUG_LOG_FILE, debug_log

    if '--debug' in sys.argv:
        import atexit
        sys.argv.remove('--debug')
        debug_active = True
        DEBUG_LOG_DIR = get_log_dir()
        DEBUG_SESSION_ID = datetime.now().strftime("%Y%m%d_%H%M%S")
        script_name = Path(__file__).stem
        DEBUG_LOG_FILE = DEBUG_LOG_DIR / f"{script_name}_debug_{DEBUG_SESSION_ID}.log"
        with open(DEBUG_LOG_FILE, "w") as f:
            f.write("=" * 70 + "\n")
            f.write(f"Debug Session - {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write(f"Script: {script_name}\n")
            f.write("=" * 70 + "\n\n")
        def debug_log(message, level=1):
            timestamp = datetime.now().strftime("%H:%M:%S.%f")[:-3]
            log_line = f"{timestamp} [DEBUG-{level}] {message}\n"
            with open(DEBUG_LOG_FILE, "a") as f:
                f.write(log_line)
            print(f"\033[34m[DEBUG-{level}]\033[0m {message}", file=sys.stderr)
        debug_log(f"Debug logging initialized: {DEBUG_LOG_FILE}", 1)

    cfg = load_config()

    if not cfg['bot_user']:
        print(f'Edit {CONFIG_FILE} and set bot_user, homeserver, allowed_users')
        sys.exit(1)

    if '--login' in sys.argv:
        asyncio.run(do_login(cfg))
        return

    creds = load_creds()
    if not creds.get('access_token'):
        print('No credentials found. Run with --login first.')
        sys.exit(1)

    try:
        asyncio.run(run_bot(cfg, creds))
    except KeyboardInterrupt:
        print('\n[matrix-taskbot] stopped')


if __name__ == '__main__':
    main()
